export const blockProjection = `
    _key,
    _type,
    title,
    content,
    caption,
    asset->{
        _id,
        url,
        metadata{
            lqip,
            dimensions
        }
    },
    table{
        rows[]{
            _key,
            cells
        }
    },
    slides[]{
        _key,
        title,
        description,
        image{
            asset->{
                _id,
                url
            }
        }
    },
    blocks[]{
        _key,
        _type,
        title,
        content,
        caption,
        asset->{
            _id,
            url,
            metadata{
                lqip,
                dimensions
            }
        },
        table{
            rows[]{
                _key,
                cells,
            }
        },
        blocks[]{
            _key,
            _type,
            title,
            content,
            caption,
            asset->{
                _id,
                url,
                metadata{
                    lqip,
                    dimensions
                }
            },
            table{
                rows[]{
                    _key,
                    cells
                }
            }
        }
    }
`

